# Generated by Django 4.0.4 on 2022-06-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(verbose_name='Общая цена')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Обложка')),
                ('basic_price', models.IntegerField(verbose_name='Базовая цена')),
                ('final_price', models.IntegerField(verbose_name='Итоговая цена')),
                ('status', models.CharField(choices=[(0, 'Черновик'), (1, 'В продаже'), (2, 'Архив')], default=0, max_length=20, verbose_name='Статус')),
                ('monthly_sales', models.IntegerField(default=0, verbose_name='Продажи за 30 дней')),
                ('monthly_cost', models.IntegerField(default=0, verbose_name='Цена за 30 дней')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(default=30, validators=[MinValueValidator(1,'Значение от 1 до 100'), MaxValueValidator(100,'Значение от 1 до 100')], verbose_name='процент скидки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('bought', models.BooleanField(default=False, verbose_name='Куплен?')),
                ('purchase_date', models.DateTimeField(blank=True, verbose_name='Дата покупки')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shop.cart')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
