# Generated by Django 4.0.4 on 2022-06-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(0, 'Черновик'), (1, 'В продаже'), (2, 'Архив')], default='0', max_length=20, verbose_name='Статус'),
        ),
    ]
