# Generated by Django 4.0.4 on 2022-06-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ONSALE', 'В продаже'), ('ARCHIVED', 'Архив')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
    ]
