# Generated by Django 4.0.4 on 2022-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(null=True, verbose_name='Итоговая цена'),
        ),
    ]
