# Generated by Django 4.0.4 on 2022-06-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem_price_orderitem_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
