# Generated by Django 4.0.4 on 2022-06-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orderitem_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
    ]
