# Generated by Django 4.0.4 on 2022-06-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orderitem_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='monthly_cost',
            field=models.IntegerField(default=0, verbose_name='Cумма продажи за 30 дней'),
        ),
    ]
